{% set name = "txmongo" %}
{% set version = "25.0.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 997ea63d0c4084aeed7f3d33aec983412f8871f6c9e53c6cbe427b6b886f2ce0

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pymongo >=3.12,<=4.10.1
    - twisted >=24.7.0

test:
  imports:
    - txmongo
    - txmongo._gridfs
    - txmongo.utils

about:
  home: https://github.com/twisted/txmongo
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Asynchronous Python/Twisted driver for MongoDB
  doc_url: https://txmongo.readthedocs.io
  dev_url: https://github.com/twisted/txmongo

extra:
  recipe-maintainers:
    - holymonson
