{% set name = "txmongo" %}
{% set version = "24.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 035acd8f6b12f25ac9b486dd8a6102d23896faaab9dc95c6ac7797b4bee6797b

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pymongo >=3.0,<4.0
    - python >=3.6
    - twisted >=14.0

test:
  imports:
    - txmongo
    - txmongo._gridfs
    - txmongo.utils

about:
  home: https://github.com/twisted/txmongo
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Asynchronous Python/Twisted driver for MongoDB
  doc_url: https://txmongo.readthedocs.io
  dev_url: https://github.com/twisted/txmongo

extra:
  recipe-maintainers:
    - holymonson
