{% set name = "txmongo" %}
{% set version = "19.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c1bfae5c46e37030b46643ed976b41122f78a3648958a7b1a3190eb6374a357e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - pymongo >=3.0
    - python
    - twisted >=14.0

test:
  imports:
    - txmongo
    - txmongo._gridfs
    - txmongo.utils

about:
  home: https://github.com/twisted/txmongo
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Asynchronous Python/Twisted driver for MongoDB
  doc_url: https://txmongo.readthedocs.io
  dev_url: https://github.com/twisted/txmongo

extra:
  recipe-maintainers:
    - holymonson
