travis:
  secure:
    BINSTAR_TOKEN: D8Zx1hl28/ZJlDADOZgeinnaBOcdAR/aQyrMHDQWqVQHGmQq3fWdj0x8mtSWiU5CC52tkGuILLDjxzOJp36fYmQFZyYu9FEqww4SUuXK+sFcLxElfHsHjFv/XDVqhlL51FN5GM20iIIBDxEh3YKzAhQt+ShsM9mezYM2ribE5qvJi9gjqtd9DP+zUHwKuir1TxNNewdtVX2SXMmviGy6TOlY026BnYNG8xSxVamwLbTD0PumihexehAKnlt8cQJwCFbXuNeevHXDe8bnnhIY+O24v+9uzPfrAWfx3oRKDh2hLq1rOoRwPN0nzHFAT3BPqj1WzWzjMwtaDuPCDCT7GQZyy+/eI79C66S+dixGhb/6/YDQwd9xUKwVhxivgBxiqnnTJVvpwR43/v0PNJmGKpMP0fKUvGOEAe11UhUwTUn31PbAYWv+Ip5gRW/6+O9ce8tOzVQob28WHBvjqJV7/SEHF2SB6iwWspKHNH44hzyqftyCOWNg91cp7qdole9zFEqKqQkugO38rD6EiLkRBKYUVOvb7ugv7D/xsF6oLQPSqMhfes1AMlvXaATwBcYhKExOF+IczfrOGR3xO/eiE4Zmng1vOSBvu54mJfs4psqoMApfuSEchdOkwX7WYStRGaQJnDkPMa9NOyiSHcmH+WEJj1GvrHeHQaDPMWz6cA4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
